# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Oaklightment
paginate:       5
baseurl:        ""
url:            "https://github.com/Oaklight/tale"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Peng DING
  url:          http://oaklight.github.io
  email:        478772665@qq.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Oaklight

# Gems
gems:
  - jekyll-paginate
