baseURL = "http://example.org/"
languageCode = "en-us"
title = "Oaklightment"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/Oaklight\">Oaklight</a> 2017"
paginate = 10

[author]
  name = "Peng"

[params]

[params.highlight]
style = "github"
languages = ["rust", "python", "c", "c++"]

[[params.social]]
url = "https://github.com/Oaklight"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.facebook.com/profile.php?id=100011896337898"
fa_icon = "fa-facebook"

[[params.social]]
url = "https://www.linkedin.com/in/peng-ding-022a23ba/"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://www.instagram.com/pengd1116/"
fa_icon = "fa-instagram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"